spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev
  application: 
    name: microcloud-config-eureka-client
server:
  port: 8201
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    
---
spring:
  profiles: tset
  application: 
    name: microcloud-config-eureka-client
server:
  port: 8202
eureka: 
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
   